<?php

/**
 * Sample API T
 * A sample API that uses a sample-site as an example to demonstrate features in the OpenAPI 3.0 specification
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DefaultController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation findUser
     *
     * .
     *
     *
     * @return Http response
     */
    public function findUser()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $tags = $input['tags'];

        $limit = $input['limit'];


        return response('How about implementing findUser as a get method ?');
    }
}
