# docker compose yml としての書き方の バージョン
version: '3.8'

# 立てるコンテナ一覧
services:
  # swagger editor (Swaggerの仕様にしたがってYAML(JSON)ファイルを編集するツール)
  swagger-editor:
    # imageで
    image: swaggerapi/swagger-editor
    # 管理コンテナ名
    container_name: ${APP_NAME}-swagger-editor
    # 利用ポート
    ports:
      - ${EDITOR_PORT:-8001}:8080
  # swagger ui (Swagger YAML(JSON)ファイルのビュワー:いつもみてる あのサイト)
  swagger-ui:
    # imageで
    image: swaggerapi/swagger-ui
    # 管理コンテナ名
    container_name: ${APP_NAME}-swagger-ui
    # 利用ポート
    ports:
      - ${UI_PORT:-8002}:8080
    # マウント
    volumes:
      # 公開する swagger形式のyamlファイル
      - ./swagger/public/openapi.yaml:/openapi.yaml
    # 環境構築
    environment:
      SWAGGER_JSON: /openapi.yaml
  # swagger openAPI(REST) mockup server 一旦作ってみる
  swagger-mockup-api:
    # imageで
    image: stoplight/prism:4
    # 管理コンテナ名
    container_name: ${APP_NAME}-swagger-mockup-api
    # 利用ポート
    ports:
      - ${MOCKUP_PORT:-8003}:4010
    # モックアップ起動
    command: mock -h 0.0.0.0 /openapi.yaml
    # マウント
    volumes:
      - ./swagger/public/openapi.yaml:/openapi.yaml
