<?php

/**
 * Sample API T
 * A sample API that uses a sample-site as an example to demonstrate features in the OpenAPI 3.0 specification
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/**
 * get findUser
 * Summary: 
 * Notes: Returns all users
 * Output-Formats: [application/json]
 */
Route::get('/users', 'DefaultController@findUser');

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
